# Generated by Django 2.1.4 on 2019-04-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, upload_to='images')),
                ('status', models.CharField(max_length=15)),
                ('designation', models.CharField(default='Designation not set', max_length=40)),
                ('created_by', models.CharField(blank=True, max_length=40)),
                ('updated_by', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_viewer', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_key_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('session_ey', models.CharField(max_length=40, unique=True)),
                ('session_data', models.CharField(max_length=40)),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
