# Generated by Django 2.1.4 on 2019-04-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_description', models.TextField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('parent_id', models.IntegerField(null=True)),
                ('category_description', models.TextField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('prodLoc_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReStock',
            fields=[
                ('restock_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=255)),
                ('restock_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barcode', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=15)),
                ('restocked_at', models.DateField(auto_now=True)),
                ('restock_updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=255)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=15)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorSku',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_sku', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('wh_id', models.AutoField(primary_key=True, serialize=False)),
                ('wh_name', models.CharField(max_length=50)),
                ('wh_address', models.TextField()),
                ('wh_city', models.CharField(max_length=20)),
                ('wh_country', models.CharField(max_length=20)),
                ('wh_phone', models.CharField(max_length=20)),
                ('wh_status', models.CharField(max_length=20)),
                ('wh_type', models.CharField(max_length=20)),
            ],
        ),
    ]
