# Generated by Django 2.1.4 on 2019-04-15 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('bundle_id', models.AutoField(primary_key=True, serialize=False)),
                ('bundle_name', models.CharField(max_length=20)),
                ('bundle_description', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BundleProducts',
            fields=[
                ('bundleprod_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField(default=2)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Bundle')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=20)),
                ('client_description', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, default='No Phone Number', max_length=30)),
                ('client_address', models.CharField(blank=True, default='No Address', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSales',
            fields=[
                ('client_sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('sales_date', models.DateField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Clients')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Stock')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='Order Id Not Specified', max_length=255, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('order_type', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Clients')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProducts',
            fields=[
                ('orderedProd_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('paid_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=20)),
                ('transaction_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Order')),
            ],
        ),
    ]
